
name: safeguard_migas
description: SafeGuard Migas Flutter App
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0

flutter:
  uses-material-design: true
dev_dependencies:
  flutter_lints: ^6.0.0
