// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJPAUA9fnlqGFzA7LbZc-n4F8naQunVnQ',
    appId: '1:436802381401:web:e7706daebdf2578c8f3348',
    messagingSenderId: '436802381401',
    projectId: 'safeguard-migas',
    authDomain: 'safeguard-migas.firebaseapp.com',
    storageBucket: 'safeguard-migas.firebasestorage.app',
    measurementId: 'G-NF967XHH8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA54KNeIWp-rqXkmiOtASmEosIw30rUqWo',
    appId: '1:436802381401:android:b39d8a1c05355b488f3348',
    messagingSenderId: '436802381401',
    projectId: 'safeguard-migas',
    storageBucket: 'safeguard-migas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWXkbfb6NUjlXPuk-t3MjvGc__S7mMVaA',
    appId: '1:436802381401:ios:b4cc5020e9a27a0b8f3348',
    messagingSenderId: '436802381401',
    projectId: 'safeguard-migas',
    storageBucket: 'safeguard-migas.firebasestorage.app',
    iosBundleId: 'com.example.safeguardMigas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWXkbfb6NUjlXPuk-t3MjvGc__S7mMVaA',
    appId: '1:436802381401:ios:b4cc5020e9a27a0b8f3348',
    messagingSenderId: '436802381401',
    projectId: 'safeguard-migas',
    storageBucket: 'safeguard-migas.firebasestorage.app',
    iosBundleId: 'com.example.safeguardMigas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJPAUA9fnlqGFzA7LbZc-n4F8naQunVnQ',
    appId: '1:436802381401:web:21952b70ef9d7ace8f3348',
    messagingSenderId: '436802381401',
    projectId: 'safeguard-migas',
    authDomain: 'safeguard-migas.firebaseapp.com',
    storageBucket: 'safeguard-migas.firebasestorage.app',
    measurementId: 'G-RER7VQW5E7',
  );
}
